# $ conda create --name <env> --file <this file>
name: prep
channels:
  - defaults
  - salilab
  - conda-forge
dependencies:
  - python
  - requests
  - openmm
  - pdbfixer
  - modeller
  - biopython
