# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: prepmd CI

on:
  push:
    branches: [main]
  pull_request:
  schedule:
    - cron: '0 8 * * 1'
  workflow_dispatch:

jobs:
  tests:
    name: Run tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, windows-2025, macos-15]
        python-version: ["3.13"]

    env:
      KEY_MODELLER: MODELIRANJE

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5.0.0

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: ${{ matrix.python-version }}
          environment-file: environment.yaml
          activate-environment: prep
          auto-update-conda: true
          auto-activate-base: false

      - name: Verify conda environment
        shell: bash -l {0}
        run: |
          conda info
          conda list

      - name: Install additional testing dependencies
        shell: bash -l {0}
        run: |
          conda install -y pytest pytest-cov

      - name: Run test suite
        shell: bash -l {0}
        run: |
          pytest --cov=prepmd --cov-report=term-missing --cov-append .
